// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ClockInterface is an autogenerated mock type for the ClockInterface type
type ClockInterface struct {
	mock.Mock
}

// GetCurrentTime provides a mock function with given fields:
func (_m *ClockInterface) GetCurrentTime() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Now provides a mock function with given fields:
func (_m *ClockInterface) Now() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

type mockConstructorTestingTNewClockInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewClockInterface creates a new instance of ClockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClockInterface(t mockConstructorTestingTNewClockInterface) *ClockInterface {
	mock := &ClockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
