// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	errors "wallet/errors"
	models "wallet/models"

	mock "github.com/stretchr/testify/mock"

	service "wallet/service"
)

// LoginServiceInterface is an autogenerated mock type for the LoginServiceInterface type
type LoginServiceInterface struct {
	mock.Mock
}

// CreateDBSession provides a mock function with given fields: userID
func (_m *LoginServiceInterface) CreateDBSession(userID uint) (*models.Session, *errors.Err) {
	ret := _m.Called(userID)

	var r0 *models.Session
	if rf, ok := ret.Get(0).(func(uint) *models.Session); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}

	var r1 *errors.Err
	if rf, ok := ret.Get(1).(func(uint) *errors.Err); ok {
		r1 = rf(userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.Err)
		}
	}

	return r0, r1
}

// DeleteDBSessionByID provides a mock function with given fields: id
func (_m *LoginServiceInterface) DeleteDBSessionByID(id uint) *errors.Err {
	ret := _m.Called(id)

	var r0 *errors.Err
	if rf, ok := ret.Get(0).(func(uint) *errors.Err); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.Err)
		}
	}

	return r0
}

// GetDBSessionByID provides a mock function with given fields: id
func (_m *LoginServiceInterface) GetDBSessionByID(id uint) (*models.Session, *errors.Err) {
	ret := _m.Called(id)

	var r0 *models.Session
	if rf, ok := ret.Get(0).(func(uint) *models.Session); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}

	var r1 *errors.Err
	if rf, ok := ret.Get(1).(func(uint) *errors.Err); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.Err)
		}
	}

	return r0, r1
}

// GetDBSessionByToken provides a mock function with given fields: token
func (_m *LoginServiceInterface) GetDBSessionByToken(token string) (*models.Session, *errors.Err) {
	ret := _m.Called(token)

	var r0 *models.Session
	if rf, ok := ret.Get(0).(func(string) *models.Session); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}

	var r1 *errors.Err
	if rf, ok := ret.Get(1).(func(string) *errors.Err); ok {
		r1 = rf(token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.Err)
		}
	}

	return r0, r1
}

// GetDBSessionByUserID provides a mock function with given fields: userID
func (_m *LoginServiceInterface) GetDBSessionByUserID(userID uint) (*models.Session, *errors.Err) {
	ret := _m.Called(userID)

	var r0 *models.Session
	if rf, ok := ret.Get(0).(func(uint) *models.Session); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}

	var r1 *errors.Err
	if rf, ok := ret.Get(1).(func(uint) *errors.Err); ok {
		r1 = rf(userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.Err)
		}
	}

	return r0, r1
}

// Login provides a mock function with given fields: args
func (_m *LoginServiceInterface) Login(args service.LoginRequest) (string, string, *errors.Err) {
	ret := _m.Called(args)

	var r0 string
	if rf, ok := ret.Get(0).(func(service.LoginRequest) string); ok {
		r0 = rf(args)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(service.LoginRequest) string); ok {
		r1 = rf(args)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 *errors.Err
	if rf, ok := ret.Get(2).(func(service.LoginRequest) *errors.Err); ok {
		r2 = rf(args)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*errors.Err)
		}
	}

	return r0, r1, r2
}

// UpdateDBSessionByID provides a mock function with given fields: id
func (_m *LoginServiceInterface) UpdateDBSessionByID(id uint) (*models.Session, *errors.Err) {
	ret := _m.Called(id)

	var r0 *models.Session
	if rf, ok := ret.Get(0).(func(uint) *models.Session); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}

	var r1 *errors.Err
	if rf, ok := ret.Get(1).(func(uint) *errors.Err); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.Err)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewLoginServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewLoginServiceInterface creates a new instance of LoginServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLoginServiceInterface(t mockConstructorTestingTNewLoginServiceInterface) *LoginServiceInterface {
	mock := &LoginServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
