// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	errors "wallet/errors"
	models "wallet/models"

	mock "github.com/stretchr/testify/mock"
)

// SessionRepoInterface is an autogenerated mock type for the SessionRepoInterface type
type SessionRepoInterface struct {
	mock.Mock
}

// GetSessionByToken provides a mock function with given fields: token
func (_m *SessionRepoInterface) GetSessionByToken(token string) (*models.Session, *errors.Err) {
	ret := _m.Called(token)

	var r0 *models.Session
	if rf, ok := ret.Get(0).(func(string) *models.Session); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}

	var r1 *errors.Err
	if rf, ok := ret.Get(1).(func(string) *errors.Err); ok {
		r1 = rf(token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.Err)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewSessionRepoInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewSessionRepoInterface creates a new instance of SessionRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSessionRepoInterface(t mockConstructorTestingTNewSessionRepoInterface) *SessionRepoInterface {
	mock := &SessionRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
