// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "wallet/context"
	errors "wallet/errors"

	mock "github.com/stretchr/testify/mock"

	models "wallet/models"

	repository "wallet/repository"
)

// UserRepoInterface is an autogenerated mock type for the UserRepoInterface type
type UserRepoInterface struct {
	mock.Mock
}

// CreateDBUser provides a mock function with given fields: ctx, userInput
func (_m *UserRepoInterface) CreateDBUser(ctx *context.Ctx, userInput *repository.CreateUserInputData) (int64, *errors.Err) {
	ret := _m.Called(ctx, userInput)

	var r0 int64
	if rf, ok := ret.Get(0).(func(*context.Ctx, *repository.CreateUserInputData) int64); ok {
		r0 = rf(ctx, userInput)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 *errors.Err
	if rf, ok := ret.Get(1).(func(*context.Ctx, *repository.CreateUserInputData) *errors.Err); ok {
		r1 = rf(ctx, userInput)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.Err)
		}
	}

	return r0, r1
}

// GetDBUserByID provides a mock function with given fields: ctx, id
func (_m *UserRepoInterface) GetDBUserByID(ctx *context.Ctx, id int) (*models.User, *errors.Err) {
	ret := _m.Called(ctx, id)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(*context.Ctx, int) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 *errors.Err
	if rf, ok := ret.Get(1).(func(*context.Ctx, int) *errors.Err); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.Err)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRepoInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepoInterface creates a new instance of UserRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepoInterface(t mockConstructorTestingTNewUserRepoInterface) *UserRepoInterface {
	mock := &UserRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
