// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	errors "wallet/errors"

	fasthttp "github.com/valyala/fasthttp"

	mock "github.com/stretchr/testify/mock"
)

// AuthMwInterface is an autogenerated mock type for the AuthMwInterface type
type AuthMwInterface struct {
	mock.Mock
}

// VerifyAuth provides a mock function with given fields: ctx
func (_m *AuthMwInterface) VerifyAuth(ctx *fasthttp.RequestCtx) *errors.Err {
	ret := _m.Called(ctx)

	var r0 *errors.Err
	if rf, ok := ret.Get(0).(func(*fasthttp.RequestCtx) *errors.Err); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.Err)
		}
	}

	return r0
}

type mockConstructorTestingTNewAuthMwInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthMwInterface creates a new instance of AuthMwInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthMwInterface(t mockConstructorTestingTNewAuthMwInterface) *AuthMwInterface {
	mock := &AuthMwInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
