// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "wallet/context"
	errors "wallet/errors"

	mock "github.com/stretchr/testify/mock"

	models "wallet/models"
)

// AuthMwInterface is an autogenerated mock type for the AuthMwInterface type
type AuthMwInterface struct {
	mock.Mock
}

// CreateDBSession provides a mock function with given fields: ctx, userID
func (_m *AuthMwInterface) CreateDBSession(ctx *context.Ctx, userID uint) (int64, *errors.Err) {
	ret := _m.Called(ctx, userID)

	var r0 int64
	if rf, ok := ret.Get(0).(func(*context.Ctx, uint) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 *errors.Err
	if rf, ok := ret.Get(1).(func(*context.Ctx, uint) *errors.Err); ok {
		r1 = rf(ctx, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.Err)
		}
	}

	return r0, r1
}

// DeleteDBSessionByID provides a mock function with given fields: ctx, id
func (_m *AuthMwInterface) DeleteDBSessionByID(ctx *context.Ctx, id uint) *errors.Err {
	ret := _m.Called(ctx, id)

	var r0 *errors.Err
	if rf, ok := ret.Get(0).(func(*context.Ctx, uint) *errors.Err); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.Err)
		}
	}

	return r0
}

// GetDBSessionByID provides a mock function with given fields: ctx, id
func (_m *AuthMwInterface) GetDBSessionByID(ctx *context.Ctx, id uint) (*models.Session, *errors.Err) {
	ret := _m.Called(ctx, id)

	var r0 *models.Session
	if rf, ok := ret.Get(0).(func(*context.Ctx, uint) *models.Session); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}

	var r1 *errors.Err
	if rf, ok := ret.Get(1).(func(*context.Ctx, uint) *errors.Err); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.Err)
		}
	}

	return r0, r1
}

// GetDBSessionByToken provides a mock function with given fields: ctx, token
func (_m *AuthMwInterface) GetDBSessionByToken(ctx *context.Ctx, token string) (*models.Session, *errors.Err) {
	ret := _m.Called(ctx, token)

	var r0 *models.Session
	if rf, ok := ret.Get(0).(func(*context.Ctx, string) *models.Session); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}

	var r1 *errors.Err
	if rf, ok := ret.Get(1).(func(*context.Ctx, string) *errors.Err); ok {
		r1 = rf(ctx, token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.Err)
		}
	}

	return r0, r1
}

// GetDBSessionByUserID provides a mock function with given fields: ctx, userID
func (_m *AuthMwInterface) GetDBSessionByUserID(ctx *context.Ctx, userID uint) (*models.Session, *errors.Err) {
	ret := _m.Called(ctx, userID)

	var r0 *models.Session
	if rf, ok := ret.Get(0).(func(*context.Ctx, uint) *models.Session); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}

	var r1 *errors.Err
	if rf, ok := ret.Get(1).(func(*context.Ctx, uint) *errors.Err); ok {
		r1 = rf(ctx, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.Err)
		}
	}

	return r0, r1
}

// UpdateDBSessionByID provides a mock function with given fields: ctx, id
func (_m *AuthMwInterface) UpdateDBSessionByID(ctx *context.Ctx, id uint) *errors.Err {
	ret := _m.Called(ctx, id)

	var r0 *errors.Err
	if rf, ok := ret.Get(0).(func(*context.Ctx, uint) *errors.Err); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.Err)
		}
	}

	return r0
}

// VerifyAuth provides a mock function with given fields: ctx
func (_m *AuthMwInterface) VerifyAuth(ctx *context.Ctx) *errors.Err {
	ret := _m.Called(ctx)

	var r0 *errors.Err
	if rf, ok := ret.Get(0).(func(*context.Ctx) *errors.Err); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.Err)
		}
	}

	return r0
}

type mockConstructorTestingTNewAuthMwInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthMwInterface creates a new instance of AuthMwInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthMwInterface(t mockConstructorTestingTNewAuthMwInterface) *AuthMwInterface {
	mock := &AuthMwInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
